WELCOME_MESSAGES = [
    "Player {member} has spawned in the {server} realm. Gear up, the adventure begins!",
    "Game Update: {member} has entered the game world of {server}. Let's roll!",
    "{member}, you've just docked at {server} starport. Welcome to the edge of gaming!",
    "Welcome, {member} to the grand arena of {server}. Let the epic battles commence!",
    "{member} has joined the quest in {server}. Ready your weapons, adventure awaits!",
    "Alert: New challenger {member} has entered the {server} arena. Let the games begin!",
    "Extra life acquired! Welcome, {member} to {server}. Prepare for a gaming journey!",
    "{member} has connected to {server} server. Ping low, spirits high!",
    "{server} has a new guild member. Welcome to the fold, {member}!",
    "New high score! {member} joined {server}. Let's set some records.",
    "Welcome, {member}. {server} server status: Epic gaming in progress!",
    "{member}, welcome to {server}. Squad assembled, victory is near!",
    "Achievement Unlocked: {member} joined {server}. Welcome to the leaderboard!",
    "Respawn point set! {member}, welcome to your new gaming home: {server}!",
    "A new hero emerges! Welcome, {member}, to the world of {server}.",
    "Gaming just got more exciting with {member} joining {server}. Welcome!",
    "{member} has landed in {server}. Prepare for thrilling adventures!",
    "Welcome aboard, {member}! {server} awaits your gaming prowess.",
    "{member} has arrived in {server} with a burst of energy. Let's go!",
    "Greetings, {member}! {server} is honored to have you in its gaming community.",
    "Welcome to {server}, {member}! Brace yourself for incredible gaming experiences.",
    "{member} has crossed the gaming threshold and entered {server}. Enjoy your stay!",
    "New player alert! {member} has joined {server}. Let's make some memories!",
    "{member} has entered {server} like a boss. Get ready for some epic moments!",
    "Welcome to the {server} realm, {member}! Adventure and glory await.",
    "{member} has arrived in {server}, bringing their gaming skills to the table.",
    "Greetings, {member}! Prepare to conquer the gaming world of {server}.",
    "A warm welcome to {member} as they embark on their gaming journey in {server}.",
    "Attention, gamers! {member} is here to join the ranks of {server}.",
    "Welcome, {member}, to the fantastic world of {server}. Enjoy your stay!",
    "{member} has just stepped into {server}, where legends are born.",
    "It's a pleasure to have you, {member}, as part of {server}'s gaming community.",
    "Welcome to the gaming paradise, {member}! {server} is ready for you.",
    "{member} has landed in {server} with their gaming prowess. Let the fun begin!",
    "Greetings, {member}! Prepare for an immersive gaming experience in {server}.",
    "Welcome, {member}, to the vibrant gaming world of {server}. Enjoy your time!",
    "A big welcome to {member} as they enter the thrilling realm of {server}.",
    "{member} has arrived in {server}, where dreams and gaming skills merge.",
    "Attention, gamers! {member} is here to conquer {server}.",
    "Welcome, {member}, to the realm of endless gaming possibilities: {server}.",
    "{member} has just joined {server}, where gamers become legends.",
    "It's an honor to have you, {member}, as part of {server}'s gaming elite.",
    "Welcome to {server}, {member}! Get ready for a gaming extravaganza.",
    "{member} has joined the adventure in {server}. Prepare for epic quests!",
    "Greetings, {member}! Brace yourself for the gaming wonders of {server}.",
    "Welcome, {member}, to the captivating gaming universe of {server}.",
    "A legendary player, {member}, joins the ranks of {server}.",
    "{member} has arrived in {server}, ready to write their gaming destiny.",
    "Attention, gamers! {member} has arrived to dominate {server}.",
    "Welcome, {member}, to the realm of gaming excellence: {server}.",
    "{member} has just entered {server}, where gaming dreams come true.",
    "It's a privilege to have you, {member}, as part of {server}'s gaming community.",
    "Welcome to {server}, {member}! Let the gaming adventures unfold.",
    "{member} has joined {server}, and the gaming world rejoices!",
    "Greetings, {member}! Prepare for an extraordinary gaming journey in {server}.",
    "Welcome, {member}, to the immersive gaming experience of {server}.",
    "A warm welcome to {member} as they embark on their gaming odyssey in {server}.",
    "{member} has arrived in {server}, ready to conquer the gaming universe.",
    "Attention, gamers! {member} is here to leave their mark on {server}."
    "Player {member} has spawned in {server}, armed with a spatula and a vendetta against cereal. Beware.",
    "Breaking: {member} just crash-landed into {server} riding a shopping cart full of rubber ducks.",
    "Alert: {member} has breached {server} with the grace of a penguin on roller skates. Watch your backs.",
    "Player {member} just spawned in {server}, carrying 47 raccoons in a trench coat. No one knows why.",
    "Player {member} is here! {server} just became a poorly written sitcom with no laugh track.",
    "Alert: {member} has entered {server}, demanding a karaoke machine and an audience of cats.",
    "Player {member} has arrived in {server}, fresh from stealing candy from a vending machine. The audacity!",
    "Breaking news: {member} just spawned in {server}, claiming to be the CEO of chaos and questionable decisions.",
    "Player {member} spawned into {server} like a raccoon breaking into a nuclear reactor. This won’t end well.",
    "Player {member} is here, bringing {server} the energy of an over-caffeinated squirrel with a power complex.",
    "Player {member} just spawned in {server}, already plotting to replace the sun with a disco ball.",
    "Brace yourselves: {member} has entered {server} wearing a cardboard crown and a cape made of spaghetti.",
    "Player {member} has spawned in {server} with the same energy as a toddler loose in a candy store.",
    "Player {member} spawned into {server}, immediately claiming they invented electricity. No proof provided.",
    "Welcome, {member}! {server} just became the setting for a very weird cooking show no one asked for.",
    "Player {member} arrived in {server} like a runaway rollercoaster powered by screaming goats.",


    
]
